server:
  port: 8080

spring:
  application:
    name: spring-ai-fly-schedule
  ai:
    #gemini 설정 -> 환경변수로 관리
    google.genai:
      api-key: ${GEMINI_API_KEY}
      chat:
        options:
          model: gemini-2.5-flash
          temperature: 0.0
          max-output-tokens: 256
          top-p: 0.9
          top-k: 40

    # Ollama 설정
    ollama:
      base-url: http://localhost:11434
#      base-url: http://ollama.java21.net <- ollama 로컬에 다운받지 않은경우는 이 주소 사용하시면 됩니다.
      chat:
        options:
          model: qwen2.5:1.5b
          temperature: 0.0
          timeout: 300s

# 로깅 설정
logging:
  level:
    com.nhnacademy.flyschedule: DEBUG
    org.springframework.ai.chat.client: DEBUG

# 공공데이터 포털 서비스 설정
data-go-kr:
  api:
    url: https://apis.data.go.kr/1613000/DmstcFlightNvgInfo
    service-key: ${DATA_GO_API_KEY}

#Google Gemini API Key(Gemini 사용 시), 공공데이터 포털 서비스 키(항공편 검색 API용)는 환경변수로 따로 관리해주세요
